import { Badge, Empty, PageHead } from "@/components/app-shell";
import { createFinding, deleteFinding, updateFinding } from "@/lib/actions";
import { createClient } from "@/lib/supabase/server";
import { severities, statuses, type Asset, type Finding, type Programme } from "@/lib/types";

export default async function FindingsPage({ searchParams }: { searchParams: Promise<{q?:string;severity?:string;status?:string}> }) {
  const filters=await searchParams; const supabase=await createClient();
  const [{data:programmeData},{data:assetData}] = await Promise.all([supabase.from("programmes").select("*").order("name"),supabase.from("assets").select("*").order("value")]);
  let query=supabase.from("findings").select("*,programmes(name),assets(value)").order("updated_at",{ascending:false});
  if(filters.q) query=query.or(`title.ilike.%${filters.q}%,description.ilike.%${filters.q}%,notes.ilike.%${filters.q}%`); if(filters.severity)query=query.eq("severity",filters.severity); if(filters.status)query=query.eq("status",filters.status);
  const {data}=await query; const findings=(data||[]) as Finding[]; const programmes=(programmeData||[]) as Programme[]; const assets=(assetData||[]) as Asset[];
  return <><PageHead title="Findings" description="Move observations through a clear human-reviewed workflow"/>
    {programmes.length?<section className="card"><h2>Create finding</h2><FindingForm action={createFinding} programmes={programmes} assets={assets}/></section>:<div className="notice warning">Create a programme before adding findings.</div>}
    <form className="card form-grid" style={{marginTop:16}}><div className="field"><label>Search</label><input name="q" defaultValue={filters.q}/></div><div className="field"><label>Severity</label><select name="severity" defaultValue={filters.severity}><option value="">All</option>{severities.map(x=><option key={x}>{x}</option>)}</select></div><div className="field"><label>Status</label><select name="status" defaultValue={filters.status}><option value="">All</option>{statuses.map(x=><option key={x}>{x}</option>)}</select></div><button className="button">Apply filters</button></form>
    <div className="stack" style={{marginTop:16}}>{findings.map(f=><article className="card" id={f.id} key={f.id}><div className="record-top"><div><h2>{f.title}</h2><div className="meta">{f.programmes?.name} · {f.assets?.value||"No asset selected"}</div></div><div className="actions"><Badge>{f.severity}</Badge><Badge>{f.status}</Badge></div></div><p>{f.description||"No description recorded."}</p><details><summary>Edit finding</summary><FindingForm finding={f} action={updateFinding} programmes={programmes} assets={assets}/></details><form action={deleteFinding} style={{marginTop:16}}><input type="hidden" name="id" value={f.id}/><button className="button danger">Delete finding</button></form></article>)}{!findings.length&&<Empty>No findings match these filters.</Empty>}</div>
  </>;
}

function FindingForm({finding,action,programmes,assets}:{finding?:Finding;action:(form:FormData)=>Promise<void>;programmes:Programme[];assets:Asset[]}){return <form action={action} className="form-grid">{finding&&<input type="hidden" name="id" value={finding.id}/>}<div className="field full"><label>Title</label><input name="title" defaultValue={finding?.title} required/></div><div className="field full"><label>Description</label><textarea name="description" defaultValue={finding?.description}/></div><div className="field"><label>Programme</label><select name="programme_id" defaultValue={finding?.programme_id} required>{programmes.map(p=><option value={p.id} key={p.id}>{p.name}</option>)}</select></div><div className="field"><label>Affected asset</label><select name="asset_id" defaultValue={finding?.asset_id||""}><option value="">Not selected</option>{assets.map(a=><option value={a.id} key={a.id}>{a.value}</option>)}</select></div><div className="field"><label>Severity</label><select name="severity" defaultValue={finding?.severity||"Medium"}>{severities.map(x=><option key={x}>{x}</option>)}</select></div><div className="field"><label>Status</label><select name="status" defaultValue={finding?.status||"New"}>{statuses.map(x=><option key={x}>{x}</option>)}</select></div><div className="field"><label>Source reference</label><input name="source_reference" defaultValue={finding?.source_reference}/></div><div className="field full"><label>Notes</label><textarea name="notes" defaultValue={finding?.notes}/></div><button className="button">{finding?"Save finding":"Create finding"}</button></form>}
